name: proyecto_final_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fl_chart: ^0.68.0 # Corrección: Usar una versión válida y reciente
  collection: ^1.18.0 # Paquete para utilidades como firstWhereOrNull
  flutter:
    sdk: flutter
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
